/*
 * This source file was generated by the Gradle 'init' task
 */


import org.junit.Test;

import lab7.Huffman;

import static org.junit.Assert.*;

public class HuffmanTest {
    @Test public void appHasAGreeting() {
        Huffman classUnderTest = new Huffman();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
